/*
** ###################################################################
**
** Copyright 2026 NXP
**
** Redistribution and use in source and binary forms, with or without modification,
** are permitted provided that the following conditions are met:
**
** o Redistributions of source code must retain the above copyright notice, this list
**   of conditions and the following disclaimer.
**
** o Redistributions in binary form must reproduce the above copyright notice, this
**   list of conditions and the following disclaimer in the documentation and/or
**   other materials provided with the distribution.
**
** o Neither the name of the copyright holder nor the names of its
**   contributors may be used to endorse or promote products derived from this
**   software without specific prior written permission.
**
** THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
** ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
** WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
** DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR
** ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
** (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
** LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
** ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
** (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
** SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
**
**
** ###################################################################
*/

/*==========================================================================*/
/*!
 * @addtogroup CONFIG_VCU_IMX95
 * @{
 *
 * @file
 * @brief
 *
 * Header file containing configuration info for the device block controls.
 */
/*==========================================================================*/

#ifndef CONFIG_BCTRL_H
#define CONFIG_BCTRL_H

/* Includes */

#include "config_user.h"

/* Defines */


/*--------------------------------------------------------------------------*/
/* BCTRL A Config                                                           */
/*--------------------------------------------------------------------------*/

/*! Config for BCTRL A */
/* Hand-copied from NXP's mx95evk reference config -- this project's .mex has
 * no representation for BCTRL at all (grep confirms zero references), so
 * SMCT always emits an empty list here regardless of project settings. This
 * project inherited an empty block-control init because it was built up
 * from scratch rather than derived from mx95evk's full reference config.
 * Confirmed on real FRDM-IMX95 hardware that a factory Linux image (booting
 * successfully to a full A55/Linux login prompt from eMMC) uses this same
 * mx95evk System Manager config, so these values are known-working on this
 * exact board, not just theoretically applicable. Will need to be
 * reapplied if this file is ever regenerated by SMCT. */
/* VCU DIAGNOSTIC: this block was hand-copied from mx95evk earlier this
 * session and confirmed to make no difference to the (separate) A55 stall
 * investigation. Tonight it's confirmed to be a genuine crash point (4 of
 * 8 writes succeed, then crashes at the 5th, addr 0x44210018) once TRDC_A
 * itself was fixed. The project's own .mex has zero representation for
 * BCTRL at all, so this was speculative from the start. Emptied to
 * unblock boot; revisit whether real BCTRL config is needed once M7 is
 * stable again. */
#define SM_BCTRL_A_CONFIG \
    { \
        SM_CFG_END \
    }


/*--------------------------------------------------------------------------*/
/* BCTRL W Config                                                           */
/*--------------------------------------------------------------------------*/

/*! Config for BCTRL W -- see note on SM_BCTRL_A_CONFIG above. */
/* VCU DIAGNOSTIC: emptied along with SM_BCTRL_A_CONFIG above -- see that
 * comment for rationale. */
#define SM_BCTRL_W_CONFIG \
    { \
        SM_CFG_END \
    }

#endif /* CONFIG_BCTRL_H */

/** @} */


